image: hashicorp/terraform:1.5.5
pipelines:
    branches:
        master:
            - step:
                name: 000base_plan
                script:
                    - cd layers/000base
                    - terraform init -backend-config="access_key=$AWS_ACCESS_KEY_ID" -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"
                    - terraform validate
                    - terraform plan -no-color -out 000base_tfplan
            - step:
                name: 000base_apply
                script:
                    - cd layers/000base
                    - terraform init -backend-config="access_key=$AWS_ACCESS_KEY_ID" -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"
                    - terraform validate
                    - terraform -auto-approve 000base_tfplan