clone:
  depth: full
pipelines:
  default:
    - step:
        name: sshcmd
        script:
        - echo "Adding Github.com to known hosts"
        - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        - git push --mirror git@github.com:CURRTIS1/Terraform-Playground.git