image: hashicorp/terraform:full
pipelines:
    branches:
        master:
            - step:
                script:
                    - terraform init -backend-config="access_key=$AWS_ACCESS_KEY_ID" -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"
                    - terraform validate
                    - terraform plan